Newpalette
NetLogo/Palette-Extension pull request #10
Opened 2021-07-16 17:46 UTC by IsaacNoel

New palette extension

2021-07-23 17:26 UTC, brandesNW requested changes
Great job producing this suite of commands.
Some changes are needed to meet coding style guidelines, and some documentation changes are also needed.

Be sure to make style changes to all the changed (versus moved) files.
Let me know if you have any questions.

**Some needed code changes** 

- No leading blank line at beginning of file.
- Imports in alphabetical order, to make them easier to find and maintain.
- An empty line is usually used between java imports and nlogo imports.
- Only one empty line after imports.
- One empty line separating methods.
- One space after keyword.
- Open curly bracket on same line as code, with space before it.
- Two space indents per level.
- Files that show wide indents may contain tabs. 
   -[This may help]( https://stackoverflow.com/questions/41848002/how-to-replace-tabs-with-spaces-in-atom)
- Delete commented out debugging code.


**Some needed documentation changes**

- Reporter or command arguments need to be in markdown italics, e.g. _argument1_.  
- Similarly for other words are in _italics_ or **bold** in the Word version of the documentation.

2021-07-23 17:26 UTC, brandesNW commented on USING.md
> +* For more information, see this [guide](https://learnui.design/blog/the-hsb-color-system-practicioners-primer.html)
I think it would be better to say
* For more information, search the web for 'hsb color system.'
rather than reference a specific site
(I did reference that site for convenience in my guide.)

2021-07-23 17:26 UTC, brandesNW commented on USING.md
> + * Extracting the component of a color          (example: palette:hue-of)
I would say 'a component' rather than 'the component.'

2021-07-23 17:26 UTC, brandesNW commented on USING.md
> -### Should I use a continuous color gradient or just a discrete color set ?
Is there a reason for removing this section? It seems fine to me

2021-07-23 17:26 UTC, brandesNW commented on USING.md
> +    - The color’s shade is a number in the range 0 to 10, not including 10 itself. (Not an official NetLogo concept at the moment.)
I would drop this line because the concept of shade number is not used further in this section.
At one time I had considered adding commands to manipulate an NL color's shade.

2021-07-23 17:26 UTC, brandesNW commented on USING.md
>  ColorBrewer has many colors where to start. ColorBrewer has three schemes Sequential, Divergent and Qualitative. The use of ColorBrewer for maps is discussed at length in this paper (Harrower, Brewer
This paragraph needs a re-write. I suggest the sentence "The use of ColorBrewer for maps is discussed at length in this paper (Harrower, Brewer 2003)."  be moved later, and possibly changed to indicate why it might be relevant for Agent Based models.

ColorBrewer provides many collections of RGB colors, organized into the categories  Sequential, Divergent and Qualitative. Choosing the right colors is a design problem, therefore there are many acceptable solutions. However, these guidelines might be useful for choosing colors in Agent Based Models:

2021-07-23 17:26 UTC, brandesNW commented on USING.md
The paper could be referenced here:

You can learn more about the use of these color collections in the original ColorBrewer paper (Harrower, Brewer 2003), which focuses on there application to maps.

2021-07-23 17:26 UTC, brandesNW commented on src/PaletteExtension.java
>          primitiveManager.addPrimitive ("scale-gradient", new ScaleGradient());
I agree with dropping the deprecation notice.

2021-07-23 17:26 UTC, brandesNW commented on src/old_Palette/ColorGradient.java
>  		//System.out.println("startColor: " + startColor);
I suggested changing the directory name "old_Palette." Netlogo directory names use lowercase, and a hyphen as a separator, such as "netlogo-core."  How about something like "color-brewer," which is more expressive. There could be a separate directory for "color-gradients."

Similarly, I suggest changing the name of alphaPrims. it could be "alpha" or "alpha-transparancy" or something else, but we use camelcase for names of variables, not directories.

2021-07-23 17:26 UTC, brandesNW commented on src/old_Palette/ColorGradient.java
> +		Graphics2D g = createGraphics();
please use the convention of two space indents, placement of open parens etc.

2021-07-23 17:26 UTC, brandesNW commented on src/old_Palette/ScaleGradient.java
>  		}
should use style guidelines.

2021-07-23 17:26 UTC, brandesNW commented on src/old_Palette/ScaleGradient.java
>  			it = colorLogoList.javaIterator ();
you can remove the iterator because it is no longer needed.

2021-07-23 17:26 UTC, brandesNW commented on src/old_Palette/ScaleGradientHSB.java
> +public class ScaleGradientHSB implements Reporter
should use style guidelines

2021-07-23 17:26 UTC, brandesNW commented on src/ColorManager.java
> +  public void setAgentColor(Context context, LogoList rgb) throws ExtensionException {
Put a space between methods. Probably applies elsewhere too.

2021-07-23 17:26 UTC, brandesNW commented on src/alphaPrims/GetAgentTransparency.java
> +
No leading blank line at beginning of file.

2021-07-23 17:26 UTC, brandesNW commented on src/alphaPrims/SetAgentTransparency.java
> +
no space needed

2021-07-23 17:26 UTC, brandesNW commented on src/hsb/HSBUpdated.java
> +    if(ind == 0) { newVal = modDouble(newVal, 360); }
remember space after keyword

2021-07-23 17:26 UTC, brandesNW commented on src/hsb/prims/ExtractBrightness.java
> +
only one empty line needed

2021-07-23 17:26 UTC, brandesNW commented on src/old_Palette/ColorGradient.java
>  		//System.out.println("endColor: " + endColor );
delete commented out debugging code

2021-07-23 17:26 UTC, brandesNW commented on src/old_Palette/ScaleGradientHSB.java
> +			Syntax.ListType() ,   // n list with lists of 3 numbers [[r g b] [r g b] ...]
list should have [h s b] ...

2021-07-23 17:26 UTC, brandesNW commented on src/old_Palette/ScaleGradientHSB.java
> +		// Validate colorList rgb arguments
hsb arguments

2021-07-23 17:26 UTC, brandesNW commented on src/old_Palette/ScaleGradientHSB.java
> +	private void validRGB( int c )
validRGB and validRGBList methods can be deleted.

2021-07-23 17:26 UTC, brandesNW commented on src/old_Palette/ScaleGradientHSB.java
> +import java.util.ArrayList;
Note for this and other files that have wide indents. The original file has tabs. the following may help
https://stackoverflow.com/questions/41848002/how-to-replace-tabs-with-spaces-in-atom

2021-07-23 17:26 UTC, brandesNW commented on src/rgb/prims/ExtractBlue.java
> +
only one empty line after imports

2021-07-23 17:26 UTC, brandesNW commented on src/rgb/prims/GetAgentBlue.java
> +import org.nlogo.api.Argument;
Note: imports are usually in alphabetical order, to make them easier to find and maintain.
An empty line is usually used between java imports and nlogo imports.

2021-07-23 17:26 UTC, brandesNW commented on tests.txt
>    extensions [palette]
Add test that shows use of an NLC in the gradient

2021-07-23 17:26 UTC, brandesNW commented on tests.txt
> +Scale-Gradient-HSB
add a test that involves varying HSB colors.
also test case where the 'range values' are reversed, and where the value to be evaluated is above or below the range.

2021-07-23 17:26 UTC, brandesNW commented on tests.txt
> +
only one blank line needed

2021-07-23 17:26 UTC, brandesNW commented on tests.txt
> +Alpha_3D
add case with 2D patch with setting non-default alpha

2021-07-23 17:26 UTC, brandesNW commented on tests.txt
> +Set-Transparency
add 2D and 3D tests

2021-07-23 17:26 UTC, brandesNW commented on documentation.conf
> +Get the alpha value of the color of the agent.The alpha value of an NL or RGB color is 255.
space after period

2021-07-23 17:26 UTC, brandesNW commented on documentation.conf
> +Reports an RGBA color with alpha component equal to number and the other RGB components of the color unchange. An error message results if alpha is not in the range from 0 to 255.
unchanged, not unchange

2021-07-23 17:26 UTC, brandesNW commented on documentation.conf
> +Set the color of the agent to the RGBA color with alpha value number and the RGB content of the color of the turtle or link to number. An error message results if number is not in the range 0 to 255.
Should read (error in original)
Set the color of the agent to the RGBA color with alpha value _number_ and the RGB content of the color of the turtle or link (or patch in NetLogo3D).  An error message results if number is not in the range 0 to 255.

2021-07-23 17:26 UTC, brandesNW commented on documentation.conf
> +Reports an RGBA color with an alpha value equivalent to percent transparency number ((100 - transparency) * 2.55) number and the RGB content of color. An error message results if number is not in the
Reports an RGBA color with an alpha value equivalent to ((100 - _number_) * 2.55) and the RGB content of _color_. An error message results if number is not in the range 0 to 100.
 


we now refer to transparency, not "percent transparency" because it goes from 0 to 100, and we don't have another version of transparancy.

also reporter or command arguments that are in italics in the Word doc need to be in markdown italics, e.g. _argument1_

2021-07-23 17:26 UTC, brandesNW commented on documentation.conf
> +Set the color of the agent to the RGBA color with alpha value number equivalent to the transparency and the RGB content of the color of the turtle or link to number. An error message results if numbe
remember to apply the comment on _set-alpha_

2021-07-23 17:26 UTC, brandesNW commented on documentation.conf
> +  Reports an RGB color equivalent to a color in HSB space proportional to number using a gradient generated with hsb-list. An hsb-list consists of a list containing three-element lists of HSB colors:
For section below, make some words _italic_ font as done in _scale-gradient_  As far as I know use of asterisk and underscore are equivalent, I don't know why that doc uses asterisk.

2021-07-23 17:26 UTC, brandesNW commented on documentation.conf
>  """
I would like to see examples of how to change the component value of an agent's alpha or color, because we don't have a command to do it.

this should probably start with a new section header - you should figure out the level

Varying an Agent's Transparency or Color

Here are two ways to make a turtle more transparent (smaller alpha, greater transparency).
A similar approach can be used with color components such as _brightness_.

```
ask turtles [ palette:set-transparency palette:transparency  + 10 ]
ask turtles [ palette:set-alpha .9 * palette:alpha ]
```

Because an error will result if the value passed to a set command is not in the correct range,  a little additional code is sometimes needed.

```
ask turtles [ palette:set-transparency min list  100 (palette:transparency + 10) ]
ask turtles [ palette:set-alpha max list 0 (palette:alpha - 25.5) ]
```

2021-07-27 20:30 UTC, brandesNW approved these changes
Looks good to go. 
Note: most file that were moved show up as renamed, but src/ColorGradient.java src/ColorGradient.java src/ScaleGradient.java show up as deleted, and reappear with their new names

2021-07-29 18:36 UTC, LaCuneta requested changes
Thanks for all your work on this!  I know NetLogo extensions can be a bit difficult to get familiar with, but you got everything covered.  I particular appreciate adding those language tests.

- `ColorManager`, `AdjustColorHSB`, `ExtractHSB`, `HSBUpdated`, `RGBUpdated` - can the methods on these classes be made static?  It doesn't appear there is a need for an instance of any of them as they track no state.
- Remove the `the_` prefixes from local variables, `the_color`, `the_rgbcolor`, etc.
- `ExtractHue`, `ExtractBrightness`, `ExtractSaturation` - these classes seem identical except for the index used in the last step of `report()` - `return extracthsb.extract(rgb, $INDEX_HERE);`.  Can they be made into a single class that takes that index as a consutrctor argument?  Like: `primitiveManager.addPrimitive("hue-of", new ExtractHSBComponent(0));`, `primitiveManager.addPrimitive("saturation-of", new ExtractHSBComponent(1));`, etc.
- `GetAgentHue`, `GetAgentBrightness`, `GetAgentSaturation` - same as above.
- `WithHue`, `WithBrightness`, `WithSaturation` - same as above.
- `ExtractRed`, `ExtractGreen`, `ExtractBlue` - same as above.
- `GetAgentRed`, `GetAgentGreen`, `GetAgentBlue` - same as above.
- `SetAgentRed`, `SetAgentGreen`, `SetAgentBlue` - same as above.
- `WithBlue`, `WithGreen`, `WithRed` - same as above.

`SetAgentHue`, `SetAgentBrightness`, `SetAgentSaturation` - These are almost "same as above" but I see their code includes a test for the given argument to be within some limit that is different for each component.  That check could be turned into an abstract method on an abstract base class that does all the work, then each separate child class would only 1) set their "index" value and 2) implement that check method (with appropriate error).  So this:

```java
    if (newValue < 0 || newValue > 360) {
      throw new ExtensionException("Hue must be in the range from 0 to 360.");
    }
```

Would become in the base class:

```java
    this.checkValue(newValue)
```

With this in the child `SetAgentHue` class:

```java
  @override
  public void checkValue(double value) {
    if (newValue < 0 || newValue > 360) {
      throw new ExtensionException("Hue must be in the range from 0 to 360.");
    }
  }
```

If I missed any other slgiht differences in the other triplets of classes, they could also probably be handled in this way.  I hope that makes sense.  Let me know if you have questions on that or anything else.

2021-07-30 14:28 UTC, LaCuneta requested changes
This looks good, really close to merging.  I left one new comment and saw one other item, explained below.

I see code like this in a few places:

```java
    try {
      // ... code that can throw an `ExtensionException`
    }
    catch (ExtensionException e) {
      throw new ExtensionException(e.getMessage());
    }
```

I can't think of a great reason to do that.  The stack trace for the inner exception will include the location in the Palette extension, so it should be clear where the issue is coming from.  Unless there is some other reason for doing this I'm not seeing, I'd just leave the exception unchanged and remove the `try/catch` entirely.  I probably should've noticed this on my first go-through, sorry!

As usual, let me know if you have any questions.

2021-07-30 14:28 UTC, LaCuneta commented on src/hsb/SetAgentHSB.java
> +    if (newValue < 0 || newValue > 100) {
I think this comparison should be against the `range[index]` and not `100`, right?

2021-07-30 17:03 UTC, LaCuneta approved these changes

2021-07-30 17:40 UTC, merged