Correct Dialog Numbers
NetLogo/Palette-Extension pull request #13
Opened 2021-08-05 15:00 UTC by IsaacNoel

2021-08-05 19:01 UTC, brandesNW requested changes
ColorSchemes needs the "usual" format changes: spaces not tabs, proper curly brackets.

I would update some of the message to sound better:
			throw new ExtensionException(
						"1 Your Scheme Type name was " + schemeType +
						" your argument can only be : " +
						"Sequential, Divergent or Qualitative" );
could become:
   throw new ExtensionException(
       "Scheme Type must be Sequential, Divergent or Qualitative" );


ColorSchemesPanel needs some { updated, and some indenting fixed. 

Otherwise looks good

2021-08-06 10:43 UTC, brandesNW requested changes
Looks good. 2 comments need to be re-indented.

in ColorSchemesPanel it says
```
        legendLabel.setText("No sequential scheme available, " +
                    "select less or equal than 10");
```
but the dialog limits it to 9, which is correct. It would be good for the error message to get the actual number from the array. Similarly for divergent. That way code won’t need to change when a new named scheme is added

2021-08-06 15:37 UTC, brandesNW approved these changes

2021-08-06 15:50 UTC, LaCuneta approved these changes

2021-08-06 15:50 UTC, merged